on: push
name: Publish Website
jobs:
  deploy_development:
    name: Deploy to development env
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Get lates code to deploy
        uses: actions/checkout@v3
      - name: Sync Files (deployment)
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER_DEV }}
          server-dir: ${{ secrets.FTP_PATH_DEV }}
          username: ${{ secrets.FTP_USERNAME_DEV }}
          password: ${{ secrets.FTP_PASSWORD_DEV }}

  deploy_production:
    name: Deploy to production env
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Get lates code to deploy
        uses: actions/checkout@v3

      - name: Sync Files (deployment)
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          server-dir: ${{ secrets.FTP_PATH }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
